
const booksData = [
    {
        title: "На маяк",
        author: "Вирджиния Вулф",
        series: "Магистраль. Главный тренд.",
        publishing: "magistr",
        image: "/image/home/header.png",
        isbn: "978-5-04-198784-8",
        ageLimit: "16+",
        originalTitle: "The Awakening",
        coverType: "Мягкая обложка",
        pages: 256,
        weight: "0 кг",
        thickness: "15 мм",
        format: "125x200 мм",
        paperMaterial: "Бумага офсетная пухлая",
        readingTime: "12 часов 48 минут",
        description: "На маяк — книга категорически необычная. Два дня, разделенные десятилетним промежутком времени...",
        category: "художественная литература"
    },
    {
        title: "Рассказ служанки",
        author: "Маргарет Этвуд",
        series: "Мировая классика",
        publishing: "АСТ",
        image: "/image/books/the-handmaid-tale.png",
        isbn: "978-5-17-118367-5",
        ageLimit: "16+",
        originalTitle: "The Handmaid's Tale",
        coverType: "Твёрдый переплёт",
        pages: 416,
        weight: "0.45 кг",
        thickness: "22 мм",
        format: "135x205 мм",
        paperMaterial: "Офсетная бумага",
        readingTime: "15 часов 30 минут",
        description: "Рассказ служанки — это знаменитая антиутопия, описывающая мир, где права женщин сведены к минимуму. История служанки Оффред раскрывает тёмные аспекты общества, основанного на контроле и репродуктивной эксплуатации.",
        category: "антиутопия"
    },

    {
        title: "Своя комната",
        author: "Вирджиния Вулф",
        series: "Феминизм и литература",
        publishing: "Азбука-Аттикус",
        image: "/image/books/a-room-of-one's-own.png",
        isbn: "978-5-389-04508-3",
        ageLimit: "12+",
        originalTitle: "A Room of One's Own",
        coverType: "Мягкая обложка",
        pages: 192,
        weight: "0.25 кг",
        thickness: "10 мм",
        format: "125x200 мм",
        paperMaterial: "Мелованная бумага",
        readingTime: "8 часов 30 минут",
        description: "Классическое эссе Вирджинии Вулф, посвящённое роли женщин в литературе. Эссе рассматривает вопрос об условиях, необходимых для творчества, и предлагает глубокий анализ культурных препятствий, стоящих перед женщинами-писателями.",
        category: "литературное эссе"

    },
    {
      title: "Пробуждение",
      author: "Кейт Шопен",
      series: "Классическая литература",
      publishing: "АСТ",
      image: "/image/books/the-awakening.png",
      isbn: "978-5-17-118342-4",
      ageLimit: "16+",
      originalTitle: "The Awakening",
      coverType: "Мягкая обложка",
      pages: 320,
      weight: "0.3 кг",
      thickness: "18 мм",
      format: "145x215 мм",
      paperMaterial: "Офсетная бумага",
      readingTime: "10 часов 15 минут",
      description: "Роман *'Пробуждение'* рассказывает историю женщины, которая пытается найти себя в условиях ограничений общества конца XIX века. Это мощное произведение об эмансипации и личной свободе.",
      category: "художественная литература"
    },
    {
      title: "Эмма",
      author: "Джейн Остин",
      series: "Классика английской литературы",
      publishing: "Азбука",
      image: "/image/books/emma.png",
      isbn: "978-5-389-07448-7",
      ageLimit: "12+",
      originalTitle: "Emma",
      coverType: "Твёрдая обложка",
      pages: 512,
      weight: "0.55 кг",
      thickness: "28 мм",
      format: "135x205 мм",
      paperMaterial: "Бумага белая",
      readingTime: "16 часов 20 минут",
      description: "Роман *'Эмма'* – одно из самых известных произведений Джейн Остин. Это уморительная, но глубокая история о любви, гордости и проницательности, написанная с искрометным юмором.",
      category: "роман"
    }
  ];
  
export default booksData;  